name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Lint client
      run: pnpm --filter client run lint

    - name: Type check client
      run: pnpm --filter client run type-check

    - name: Lint server
      run: pnpm --filter server run lint

    - name: Type check server
      run: pnpm --filter server run type-check
